-- DROPS TABLES
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS characteristics CASCADE;
DROP TABLE IF EXISTS characteristics_reviews CASCADE;
DROP TABLE IF EXISTS photos CASCADE;

-- REVIEWS TABLE

CREATE TABLE reviews (
  review_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  product_id INTEGER NOT NULL,
  rating SMALLINT NOT NULL,
  date BIGINT NOT NULL,
  summary VARCHAR NOT NULL,
  body TEXT NOT NULL,
  recommend BOOLEAN NOT NULL,
  reported BOOLEAN NOT NULL,
  reviewer_name VARCHAR (30) NOT NULL,
  reviewer_email VARCHAR (50) NOT NULL,
  response TEXT NULL DEFAULT NULL,
  helpfulness SMALLINT NOT NULL
);

COPY reviews FROM '/Users/olivia-home/hackreactor/immersive/SDC/csv/reviews.csv' WITH (FORMAT csv, HEADER TRUE);

-- CHARACTERISTICS TABLE

CREATE TABLE characteristics (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  product_id INTEGER NOT NULL,
  name VARCHAR (60) NOT NULL
);

COPY characteristics FROM '/Users/olivia-home/hackreactor/immersive/SDC/csv/characteristics.csv' WITH (FORMAT csv, HEADER TRUE);

-- CHARACTERISTICS_REVIEWS TABLE

CREATE TABLE characteristics_reviews (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  characteristics_id INTEGER NOT NULL,
  reviews_id INTEGER NOT NULL,
  value SMALLINT NOT NULL
);

ALTER TABLE characteristics_reviews ADD FOREIGN KEY (reviews_id) REFERENCES reviews (review_id);
ALTER TABLE characteristics_reviews ADD FOREIGN KEY (characteristics_id) REFERENCES characteristics (id);

COPY characteristics_reviews FROM '/Users/olivia-home/hackreactor/immersive/SDC/csv/characteristic_reviews.csv' WITH (FORMAT csv, HEADER TRUE);

-- PHOTOS TABLE

CREATE TABLE photos (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY UNIQUE,
  review_id INTEGER NOT NULL,
  url VARCHAR NULL DEFAULT NULL
);

ALTER TABLE photos ADD FOREIGN KEY (review_id) REFERENCES reviews (review_id);

COPY photos FROM '/Users/olivia-home/hackreactor/immersive/SDC/csv/reviews_photos.csv' WITH (FORMAT csv, HEADER TRUE);
